# Generated by Django 5.2.6 on 2025-09-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='balances/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=30)),
                ('group_name', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='reports.balanceupload')),
            ],
        ),
    ]
