# Generated by Django 5.2.6 on 2025-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceupload',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
