# Generated by Django 5.2.6 on 2025-09-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_generatedfile_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceupload',
            name='summary_data',
        ),
    ]
