# Generated by Django 5.2.6 on 2025-09-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_balanceupload_summary_data'),
        ('reports', '0004_remove_generatedfile_file'),
    ]

    operations = [
    ]
