# Generated by Django 5.2.6 on 2025-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_merge_20250912_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceupload',
            name='coherence_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balanceupload',
            name='feuilles_maitresses_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balanceupload',
            name='tft_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
