# Generated by Django 5.2.6 on 2025-09-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_balanceupload_coherence_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceupload',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaire pour cette feuille maîtresse', null=True),
        ),
    ]
