# Generated by Django 5.2.6 on 2025-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_balanceupload_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceupload',
            name='comment',
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaire pour cette feuille maîtresse', null=True),
        ),
    ]
